### ISSUE TITLE
[Catalog] [MVP] Add a way to get other offers for some given options

### ISSUE THREAD

**Issue by hectorj** [wizaplace/wizaplace-php-sdk#174]
Dans le cas des MVPs, on a besoin de pouvoir obtenir les offres des autres vendeurs pour une combinaison d'options.

Ca ressemblerait à `\Wizaplace\SDK\Catalog\Product::getDeclinationFromOptions`, sauf que ca peut renvoyer + d'une déclinaison (et il faut pouvoir filtrer le vendeur courant).

**Comment by KuiKui** [comment]
So FAT !

**Comment by hectorj** [comment]
Released in v0.11.0
