### ISSUE TITLE
Ajout multiple de produits dans le panier

### ISSUE THREAD

**Issue by ngdo-pro** [wizaplace/wizaplace-php-sdk#286]
API:
https://sandbox.wizaplace.com/api/v1/doc/#tag/Basket%2Fpaths%2F~1basket~1%7BbasketId%7D~1bulk-add%2Fpost

**Comment by hectorj** [comment]
Issue moved to [wizaplace/wizaplace #4615](https://github.com/wizaplace/wizaplace/issues/4615) via [**ZenHub**](https://www.zenhub.com/)
