### ISSUE TITLE
Champs manquants dans l'Order (par rapport à l'API)

### ISSUE THREAD

**Issue by ngdo-pro** [wizaplace/wizaplace-php-sdk#289]
```
"user_id": 456,
"email": "customer@example.com",
"basket_id": "c3818958-2089-3549-b4ab-66a5c07b77dc",

"discount": 10.5,
"shipping_cost": 20,
"invoice_number": "NUM-1234",

"promotions": {
"e952b851-8768-37f5-9baf-427fea491e86": {}
},
"need_shipping": true,
"shipping": [
{}
],
"shipment_ids": [
12
],
"taxes": [ ],
"notes": "string",
```

Le besoin qui a permis de relever les manques était sur `shipping_cost`, mais après verif, il n'y a pas la liste au dessus dans le SDK. A voir ce qu'on veut faire.

**Comment by hectorj** [comment]
Issue moved to [wizaplace/wizaplace #4699](https://github.com/wizaplace/wizaplace/issues/4699) via [**ZenHub**](https://www.zenhub.com/)
